### ISSUE TITLE
Substitution done only in uppercase

### ISSUE THREAD

**Issue by szaghi** [danprince/vimsaurus#1]
First of all, thank your very much for this great plugin!

Despite of your screencast, when I perform a _vimsaurus_ substitution the substitute word is UPPERCASE no matter is the case of the substituted original word. Is this due to some settings of mine or is it a bug?

Thank you again!

**Comment by danprince** [comment]
Check it out running the word against the `bashsaurus` command. It should always come back lowercase. Then failing that, substitute a word in Vim, and run `:messages`. if you are using the latest version of vimsaurus and you can see the message `Word is capitalized`, then there's definitely a bug with the script.

Do you have any Regex specific settings turned on? If you don't think so, try experimenting with the Regex used to check uppercase words.

``` vim
:echom "testword" =~ "^[A-Z]*$"
```

This will print 1 when it matches and 0 when it fails. If you can find a variation that works for you, let me know and I'll swap it out.

**Comment by szaghi** [comment]
Thank you very much for quick replay.

After substituting a word with the latest vimsaurus the `:messages` returns

``` shell
Word is capitalized
```

**Comment by danprince** [comment]
Have you tried running that Regex against a non-uppercased word to see what happens?

**Comment by szaghi** [comment]
Sorry, yes I tried. Running `:echom "testword" =~ "^[A-Z]*$"` I obtains `1`

**Comment by danprince** [comment]
Ok, then there must be something wrong with your Vim config/settings. That Regex should only return 1 if all the letters between the start `^` and the `$` are capitals. If you want to put your Vimrc in a gist, I'll have a play with it locally.

**Comment by szaghi** [comment]
it is [here](https://github.com/szaghi/dotfiles/blob/master/vim/vimrc). However, it is long, I cannot ask you to read it. Thank you very much.

**Comment by danprince** [comment]
Ok, I've found the problem. If I remove line 106 from your Vimrc it works.

``` vim
set ignorecase                                                           " ignore case when searching
```

From [the depths](http://vimdoc.sourceforge.net/htmldoc/usr_41.html) of the Vim documentation: 

> The 'ignorecase' option is used when comparing strings.  When you don't want that, append "#" to match case and "?" to ignore case.  Thus "==?" compares two strings to be equal while ignoring case.  And "!~#" checks if a pattern doesn't match, also checking the case of letters.  For the full table see |expr-==|.

Seems like simply throwing a hash behind the operator will overload the local case settings.

``` vim
" this uses the local case settings
:echom "testword" =~ "^[A-Z]*$"

" this forces it to be case sensitive
:echom "testword" =~# "^[A-Z]*$"
```

I'll get this fixed now.

**Comment by szaghi** [comment]
Great!!!! Many many thanks!

I use ignorecase for diff: fortran (my main programming language) is case insensitive. Sorry for not remember this.
